version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'local-db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
